### ISSUE TITLE
question on gen_candidates.py

### ISSUE THREAD

**Issue by jind11** [thunlp/SememePSO-Attack#2]
Hi, I have carefully read your implementation of "gen_candidates.py". I have one question: the basic approach to get synonym candidates based on Hownet is that two words having the same POS and the same sememe set would be considered to be synonyms, is it right? Then is is really necessary for the lines 127, 128, 135 in this file (https://github.com/thunlp/SememePSO-Attack/blob/491e9488dc6dc9fd5b8b09ed7c8b2ed888e96f2c/SST/gen_candidates.py#L127)? And these three lines of code are not fair to small datasets to be attacked since many words in those small datasets may present only one or two POS tags but in fact they can have more than 2 POS tags in a large-scale corpora. Could you help check the algorithm here?
BTW, the OpenHowNet presents another way to obtain synonyms for each word, have you tried that one and compared it with your currently used method? 
Thank you so much!

**Comment by yangalan123** [comment]
I have forwarded your question to the corresponding code author. Hopefully, he can help provide better explaination. Let me quickly explain what I have learned so far:
1) The basic approach to get synonym candidates based on HowNet:  Your understanding is basically correct. Please refer to page 4 of our [paper](https://arxiv.org/pdf/1910.12196.pdf), you can find that we do restrict the candidates must have the same pos-tags as the original words to preserve grammatically. However, considering the polysemy, if the sememe set of **certain sense** of the original words is the same as **some sense** of the candidates, then they are considered "synonym based on HowNet". So the original words and the candidates do not necessarily have the same sememe set -- if the sememe set of certain sense can match, then they are synonym. A better solution might be doing word sense disambiguation here and we just leave it for our future work.

2) For pos tagging part, I have to double-check with the author @zangy17 about the detailed implementation. But let's first check my understanding about your question is correct. You mean, when applying our algorithm on small dataset, since some words may have few pos-tags, then it might be possible we miss some promising candidates due to the pos-tag constraints mentioned in 1) ? If so, when choosing the candidates, we always use the full pos-tag annotations in HowNet. For example, if certain words are annotated with "verb" and "noun" in HowNet, we will use it on both "small dataset" and "large dataset" when we are creating candidate list for the victim word.

3) I am one of the developers of OpenHowNet as well so you find the right person to ask this question! Yes, we have tried using the similarity computation utility in OpenHowNet, but there are mainly two drawbacks.  On one hand, it is not efficient, pre-computing similarity using OpenHowNet utility may take much time and we just use a simple but effective version. On the other hand, the result of using OpenHowNet similarity computation is not very promising since it enforces too strict constraints on the sememe structure of the original word and candidates. The structural annotation of HowNet is not perfect and lacks consistencies across words. (Hopefully you will see a much improved version in the future! I have known some linguistic/NLP researchers working on it.) As a result, we choose to use our simpler version of HowNet similarity computation.

Hope that helps and sorry for the late reply.

**Comment by jind11** [comment]
Hi, thanks for the explanation! However, I am still doubting the necessity of lines 127, 128 and 135 in the file of  gen_candidates.py. Actually, the basic idea of this file is to get a synonym candidates bank, where each word should find its synonyms list for each of its sense in the vocabulary. Then the construction of such a bank should not depend on any specific dataset, which means that we can build this bank once for all datasets. Is it true?

**Comment by yangalan123** [comment]
For line 127, 128 and 135, I have forwarded your question to the code author @zangy17  so please wait for some time. For the second half of the problem, I think if you use the whole vocabulary in HowNet instead of using the local vocabulary of the target dataset, then yes, once created, the candidate bank can be used in many other datasets.  BTW, we load the local vocabulary in line 6 and line 7 of `gen_candidates.py`.  However, you have to be very careful about this -- when replacing certain words that are never seen for the model, such "attack" may not be fair for the adversarial evaluation and comparisons of the attack models, because whether OOV should be regarded as a "bug" of current models is a controversial topic.  Here we just want to avoid such problem and use the local vocabulary. Another benefit of using local vocabulary is that it can boost I/O by a lot, considering HowNet vocabulary is really large.

**Comment by zangy17** [comment]
For 127,128 and 135, the codes are to make sure that the substitutions have the same inflection as the original word. For example, if the original word is "likes", we want to make sure that the substitution is "loves" instead of "love". And the substitutions are depended on dataset since we want to avoid the OOV substitutions.

**Comment by jind11** [comment]
Got it! Thanks for the explanations! Yeah, I agree that whether OOV could be a valid bug is controversial.
